// Japanese static gloss overrides used by the annotation pipeline.
// Keys must all be lower case.
const japaneseGlossOverrides: Record<string, string> = {
	"あなた":"you",
	"彼女":"she",
	"います":"is",
	"あります":"is",
	"に":"in",
	"物":"thing",
	"もの":"thing",
	"どんな":"what",
	"いただけ":"can receive",
	"頂け":"can receive",
	"ごめんなさい":"sorry",
	"着":"wear",
	"その":"that",
	"する":"do",
	"して":"do",
	"したい":"do want",
	"あそこ":"over there",
	"は":":",//"(TOP)",
	"が":";",//"(SBJ)",
	"通っ":"through",
	"ではありません":"is not",
	"か":"or",
	"ない": "not",
	"ご飯": "rice",
	"ありません": "none",
	"たい": "want",
	"ます": "(polite)",
	"ございます": "exists",
	"の": "'s",
	"年寄": "old person",
	"取っ": "take",
	"テレビ": "tv",
	"たく": "want",
	"でき": "can",
	"聞こえ":"can hear",
	"飲ん":"drink",
	// These are more likely actually part of words that were overly tokenized.
	"て":"-",
	"で":"-",
	"い":"-",
	"られ":"be",
	"た":"-",
	"し":"-",
	"さ":"-",
	// .
	"通過":"passage",
	"ポーション":"potion",
	"ロック":"rock / lock",
	"されます":"done",
	"難易度":"difficulty",
	// ❗️ 20240516 - NOTE: We will deprecate static gloss overrides. All edits should be made in SUPABASE.WORDS.
};

export default japaneseGlossOverrides;
